### ISSUE TITLE
Unable to read from camera

### ISSUE THREAD

**Issue by FaustoBrenner** [chenxinfeng4/ffmpegcv#20]
Hello, I've just installed the package and was trying to do a simple camera capture to try it out. So I ran the following code and got the error bellow.
```
import ffmpegcv
cap = ffmpegcv.VideoCaptureCAM(0)
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\dev\code\faze-exercise\venv\Lib\site-packages\ffmpegcv\__init__.py", line 330, in VideoCaptureCAM
    return FFmpegReaderCAM.VideoReader(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\code\faze-exercise\venv\Lib\site-packages\ffmpegcv\ffmpeg_reader_camera.py", line 277, in VideoReader
    id_device_map = query_camera_devices()
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\code\faze-exercise\venv\Lib\site-packages\ffmpegcv\ffmpeg_reader_camera.py", line 94, in query_camera_devices
    result = {
             ^
  File "C:\dev\code\faze-exercise\venv\Lib\site-packages\ffmpegcv\ffmpeg_reader_camera.py", line 59, in _query_camera_divices_win
    assert len(matches) == len(alternative_names)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```
To further explore the error I ran:
```
from ffmpegcv.ffmpeg_reader_camera import query_camera_devices
devices = query_camera_devices()
```
And got the error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\dev\code\faze-exercise\venv\Lib\site-packages\ffmpegcv\ffmpeg_reader_camera.py", line 94, in query_camera_devices
    result = {
             ^
  File "C:\dev\code\faze-exercise\venv\Lib\site-packages\ffmpegcv\ffmpeg_reader_camera.py", line 59, in _query_camera_divices_win
    assert len(matches) == len(alternative_names)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

I am running an environment with Python 3.11.2, and ffmpegcv is version 0.3.3. I got ffmpeg version 6.0.

**Comment by chenxinfeng4** [comment]
#17 The same issue.  Please update the ffmpegcv. And test whether it works for your.  I'll release this version after testing in days.

```
pip install -U git+https://github.com/chenxinfeng4/ffmpegcv`
``

**Comment by FaustoBrenner** [comment]
It worked, thanks!
