### ISSUE TITLE
Cannot read frame to GPU as a torch tensor

### ISSUE THREAD

**Issue by giapvn** [chenxinfeng4/ffmpegcv#51]
Hi all.
I am testing this lib for reading frames from a video file to GPU memory. I read successfully video file to GPU in pycuda array as well as mem_alloc. However, it is an error when I do same thing for torch tensor format. The below is my code:
```
cap = ffmpegcv.toCUDA(ffmpegcv.VideoCaptureNV("sample_720p.mp4", pix_fmt='nv12'))
frame_count = 0
while True:
    ret, frame_CHW_CUDA = cap.read_torch()
    if not ret:
        break
    frame_count = frame_count + 1
    pass
```
And this is my all received message:
```
Traceback (most recent call last):
  File "/app/main.py", line 60, in <module>
    ret, frame_CHW_CUDA = cap.read_torch()
  File "/usr/local/lib/python3.10/dist-packages/ffmpegcv/ffmpeg_reader_cuda.py", line 247, in read_torch
    self.converter(cuda.In(frame_yuv420p), tensor_proxy.gpudata, 
  File "/usr/local/lib/python3.10/dist-packages/pycuda/driver.py", line 481, in function_call
    func._set_block_shape(*block)
pycuda._driver.LogicError: cuFuncSetBlockShape failed: invalid resource handle
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:: Broken pipe
```
Can anyone support me for this issue?
Thanks in advance.

**Comment by chenxinfeng4** [comment]
Seems strange. Can you send me the video via link? I'll check it in my PC.

**Comment by giapvn** [comment]
I am using video sample_720p.mp4 in deepstream sample videos. Can you take it from deepstream lib please?

**Comment by chenxinfeng4** [comment]
I didn't use the deepstream yet. You'd better send me the video (or link), so that i can test.

**Comment by giapvn** [comment]
https://drive.google.com/file/d/12JgPm9HARv7rsSqDZ-0qcGD4cUA9FiXP/view?usp=sharing
This is the link to the sample video.

**Comment by chenxinfeng4** [comment]
![image](https://github.com/user-attachments/assets/01ec2f8f-eb68-49a4-a512-d416e98f9d4f)
Looks good for me. You'd better check your pycuda installation. Jump and read the pycuda website.

**Comment by giapvn** [comment]
Thanks Feng.
Could you show me your libs and others version such as pycuda, pytorch, Cuda-toolkit, ffmpeg, linux,...

**Comment by chenxinfeng4** [comment]
```
$pip list
Package                       Version              Editable project location
----------------------------- -------------------- -------------------------------------------------------
ffmpegcv                      0.3.15
imageio                       2.8.0
imageio-ffmpeg                0.4.7
importlib-metadata            4.11.3
importlib-resources           5.2.0
keras                         2.7.0
numexpr                       2.7.3
numpy                         1.21.6
nvidia-ml-py                  11.495.46
opencv-contrib-python         4.9.0.80
opencv-python                 4.8.0.76
opencv-python-headless        4.10.0.84
Pillow                        9.3.0
pip                           22.3.1
pynvjpeg                      0.0.13
tensorboard                   2.10.1
tensorboard-data-server       0.6.1
tensorboard-plugin-wit        1.8.1
tensorflow                    2.7.0
tensorflow-estimator          2.7.0
tensorflow-io-gcs-filesystem  0.27.0
tensorrt                      8.6.0
torch                         1.11.0
torch-tb-profiler             0.4.0
torch2trt                     0.4.0
torchaudio                    0.11.0
torchvision                   0.12.0
tornado                       6.2
tqdm                          4.64.0
cupy-cuda11x                  11.1.0
pycuda                        2022.1


$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0

$ nvidia-smi
NVIDIA-SMI 550.54.14 
Driver Version: 550.54.14
CUDA Version: 12.4

cuda/11.5.1, cudnn/8.8.0, tensorrt/8.6.0.12

$ ffmpeg
ffmpeg version N-105236-gebf1d0f4bb Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --pkg-config-flags=--static --enable-nonfree --enable-gpl --enable-version3 --enable-libmp3lame --enable-libvpx --enable-libopus --enable-opencl --enable-libxcb --enable-opengl --enable-nvenc --enable-vaapi --enable-vdpau --enable-ffplay --enable-ffprobe --enable-libxvid --enable-libx264 --enable-libx265 --enable-openal --enable-openssl --enable-cuda-nvcc --enable-cuvid --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64

$ uname -a
Linux aililab 5.15.0-107-generic #117~20.04.1-Ubuntu SMP Tue Apr 30 10:35:57 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by giapvn** [comment]
It is wonderful that I was successful in running it with version of libs you shown. I found out that version of `pycuda` (2022.1) and `torch` (1.11.0) are very important. When I use `CUDA Toolkit v12.x`, I must install `pycuda` v2024.1 and the latest version (2.4.0) of `torch`. After that it is sure that I will meet the above error in `read_torch()` function.
Besides, I also tested by installing the right configuration (on x86_64 machine) of libs on NVIDIA Jetson AGX Orin device (aarch64 architecture) and FFMPEGCV cannot work there. I hope that you

**Comment by chenxinfeng4** [comment]
Great to hear your feedback.
I didn't have a Jetson board right now. I'll test the Jeston board until I get such a project. Though I think AGX Orin is a high-end edge inference board, the Jeston is not my first choice for the edge. The compatible with Jetson series will probably take long time.
